spring.application.name=MyNewProject
server.port=8081

#database
spring.datasource.url=jdbc:mysql://localhost:3306/KNOW_YOUR?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Gaurav@123
spring.jpa.hibernate.ddl-auto=update



#ai
#gemini.api.key=AIzaSyCJFB3UBzP8wP5TuqfFa7iX7d3G_l0ynqY
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

spring.ai.google.genai.api-key=AIzaSyCJFB3UBzP8wP5TuqfFa7iX7d3G_l0ynqY
spring.ai.google.genai.chat.options.model=gemini-flash-latest




spring.security.user.name=admin
spring.security.user.password=admin123

##redis
spring.redis.host=localhost
spring.redis.port=6379






