spring.application.name=MyNewProject
#server.port=8081

#database
spring.datasource.url=jdbc:mysql://localhost:3306/KNOW_YOUR?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Gaurav@123
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${MYSQLUSER}
#spring.datasource.password=${MYSQLPASSWORD}
#spring.jpa.hibernate.ddl-auto=update



#ai
#gemini.api.key=AIzaSyC78saCo2Xgt6OyWh9Nf_Y7LCcuvAUeuHw
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

spring.ai.google.genai.api-key=${API_KEY}
spring.ai.google.genai.chat.options.model=gemini-flash-latest


#curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=AIzaSyC78saCo2Xgt6OyWh9Nf_Y7LCcuvAUeuHw" -H "Content-Type: application/json" -X POST -d "{\"contents\": [{\"parts\":[{\"text\": \"Write a haiku about coding.\"}]}]}"




spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.security.user.name=admin
spring.security.user.password=admin123

##redis
spring.redis.host=localhost
spring.redis.port=6379






